export const movies = [
  {
    id: 1,
    img: "/Black_Widow.png",
    title: "Black Widow",
    rate: 6.8,
  },
  {
    id: 2,
    img: "/Shang_Chi.jpg",
    title: "Shang Chi",
    rate: 7.9,
  },
  {
    id: 3,
    img: "/Loki.jpg",
    title: "Loki",
    rate: 8.4,
  },
  {
    id: 4,
    img: "/How_i_met_your_mother.jpg",
    title: "sokol",
    rate: 8.3,
  },
  {
    id: 5,
    img: "/Money_heist.jpg",
    title: "How I Met Your Mother",
    rate: 8.3,
  },
  {
    id: 6,
    img: "/Friends.jpg",
    title: "Money Heist",
    rate: 8.8,
  },
  {
    id: 7,
    img: "/The_big_bang_theory.jpg",
    title: "Friends",
    rate: 8.1,
  },
  {
    id: 8,
    img: "/Two_and_a_half_man.jpg",
    title: "The Big Bang Theory",
    rate: 7,
  },
];

export const card_details = [
  {
    id: 1,
    upper1: "MaileHereko",
    upper2: "Movies",
    img: "/Black_Widow.png",
    title: "Black Widow",
    title2: "Part of the journey is the end",
    rate: 6.8,
    description:
      "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    rate: "8.3",
    type: "Movie",
    release_date: "2019-04-24",
    run_time: "181 min",
    genres: "Adventure, Science Fiction, Action",
  },
  {
    id: 2,
    upper1: "Shang Chi",
    upper2: "Movies",
    img: "/Shang_Chi.jpg",
    title: "Black Widow",
    title2: "Part of the journey is the end",
    rate: 6.8,
    description:
      "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    rate: "8.3",
    type: "Movie",
    release_date: "2019-04-24",
    run_time: "181 min",
    genres: "Adventure, Science Fiction, Action",
  },
  {
    id: 3,
    upper1: "Loki",
    upper2: "Movies",
    img: "/Loki.jpg",
    title: "Loki",
    title2: "Part of the journey is the end",
    rate: 6.8,
    description:
      "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    rate: "8.3",
    type: "Movie",
    release_date: "2019-04-24",
    run_time: "181 min",
    genres: "Adventure, Science Fiction, Action",
  },
  {
    id: 4,
    upper1: "How I Met Your Mother",
    upper2: "Movies",
    img: "/How_i_met_your_mother.jpg",
    title: "Black Widow",
    title2: "Part of the journey is the end",
    rate: 6.8,
    description:
      "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    rate: "8.3",
    type: "Movie",
    release_date: "2019-04-24",
    run_time: "181 min",
    genres: "Adventure, Science Fiction, Action",
  },
  {
    id: 5,
    upper1: "Money Heist",
    upper2: "Movies",
    img: "/Money_heist.jpg",
    title: "Black Widow",
    title2: "Part of the journey is the end",
    rate: 6.8,
    description:
      "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    rate: "8.3",
    type: "Movie",
    release_date: "2019-04-24",
    run_time: "181 min",
    genres: "Adventure, Science Fiction, Action",
  },
  {
    id: 6,
    upper1: "Friends",
    upper2: "Movies",
    img: "/Friends.jpg",
    title: "Black Widow",
    title2: "Part of the journey is the end",
    rate: 6.8,
    description:
      "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    rate: "8.3",
    type: "Movie",
    release_date: "2019-04-24",
    run_time: "181 min",
    genres: "Adventure, Science Fiction, Action",
  },
  {
    id: 7,
    upper1: "The Big Bang Theory",
    upper2: "Movies",
    img: "/The_big_bang_theory.jpg",
    title: "Black Widow",
    title2: "Part of the journey is the end",
    rate: 6.8,
    description:
      "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    rate: "8.3",
    type: "Movie",
    release_date: "2019-04-24",
    run_time: "181 min",
    genres: "Adventure, Science Fiction, Action",
  },
  {
    id: 8,
    upper1: "Two And a Half Men",
    upper2: "Movies",
    img: "/Two_and_a_half_man.jpg",
    title: "Black Widow",
    title2: "Part of the journey is the end",
    rate: 6.8,
    description:
      "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    rate: "8.3",
    type: "Movie",
    release_date: "2019-04-24",
    run_time: "181 min",
    genres: "Adventure, Science Fiction, Action",
  },
];
